name: feat
description: "A new Flutter project for Feat."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker:
  permission_handler:
  http:
  flutter_svg:
  camera:
  path_provider:
  audioplayers:
  flutter_screenutil: ^5.8.4
  mime:
  http_parser:
  shared_preferences: ^2.3.2
  dio:
  volume_controller:
  intl:
  device_info_plus:
  flutter_local_notifications:
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.1.3
  flutter_native_splash:

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: Colors.black
  image: "assets/logo.png"
